export enum ActionTypes {
    DRAW_LISTS = "DRAW_LISTS",
    SELECT_WEEK = "SELECT_WEEK",
    REQUEST_GET_LIST = "REQUEST_GET_LIST",
    REQUEST_ADD_LIST = "REQUEST_ADD_LIST",
    REQUEST_DELETE_LIST = "REQUEST_DELETE_LIST",
    SHOW_MODAL = "SHOW_MODAL",
    HIDE_MODAL = "HIDE_MODAL",
}
